//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOBILEVECTOR.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cheque
    {
        public int IdCheque { get; set; }
        public string Date { get; set; }
        public int IdClient { get; set; }
        public int IdEmployee { get; set; }
        public int IdPart { get; set; }
        public int IdUser { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Part Part { get; set; }
        public virtual Users Users { get; set; }
    }
}
