//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOBILEVECTOR
{
    using System;
    using System.Collections.Generic;
    
    public partial class cheque
    {
        public int id_cheque { get; set; }
        public System.DateTime date { get; set; }
        public int id_client { get; set; }
        public int id_employee { get; set; }
        public int id_part { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual employee employee { get; set; }
        public virtual part part { get; set; }
    }
}
