//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOBILEVECTOR
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MOBILEVECTOREntities : DbContext
    {
        public MOBILEVECTOREntities()
            : base("name=MOBILEVECTOREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cheque> cheque { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<employee> employee { get; set; }
        public virtual DbSet<part> part { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
